comics/comics/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings

urlpatterns = patterns('',

    url(r'', include('reader.urls', namespace='reader')),
    url(r'^admin/', include(admin.site.urls)),
)

if settings.DEBUG:
     from django.conf.urls.static import static
     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

comics/reader/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('reader.views',
    url(r'^$', 'custom_login', {'template_name': 'reader/login.html'}, name='login'),
    url(r'^comic/$', 'comic_list', name='comic_list'),
    url(r'^comic/(?P<slug>[^/]+)/$', 'comic_detail', name='comic_detail'),
    url(r'^comic/(?P<slug>[^/]+)/(?P<issue>\d+)/(?P<number>\d+)/$', 'page', name='page'),
)

urlpatterns += patterns('',
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': 'reader:login'}, name='logout'),
)

comics/reader/models.py
from django.core.urlresolvers import reverse
from django.db import models
from django.contrib.auth.models import User


class TimestampsModel(models.Model):
    createTime = models.DateTimeField(auto_now_add=True)
    updateTime = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Comic(TimestampsModel):
    name = models.CharField(max_length=150)
    description = models.TextField(blank=True)
    cover = models.ImageField(blank=True, null=True, upload_to='cover')
    slug = models.SlugField(unique=True)
    publisher = models.CharField(max_length=100)
    release_date = models.DateField()


class Issue(TimestampsModel):
    comic = models.ForeignKey('Comic')
    number = models.IntegerField()
    title = models.CharField(max_length=200)

    class Meta:
        unique_together = ('comic', 'number')


class Page(TimestampsModel):
    issue = models.ForeignKey('Issue')
    page_number = models.PositiveIntegerField()
    image = models.ImageField(upload_to=lambda instance, filename: "%s/%s/%s.jpg" % (instance.issue.comic.slug, instance.issue.number, instance.page_number))

    def before(self):
        page_number = max(1, self.page_number-1)
        kwargs = {"slug": self.issue.comic.slug, 'issue': self.issue.number, 'number': page_number}
        return reverse("reader:page", kwargs=kwargs)

    def next(self):
        count = self.issue.page_set.all().count()
        page_number = min(count, self.page_number+1)
        kwargs = {"slug": self.issue.comic.slug, 'issue': self.issue.number, 'number': page_number}
        return reverse("reader:page", kwargs=kwargs)

    class Meta:
        unique_together = ('issue', 'page_number')


class Comment(TimestampsModel):
    page = models.ForeignKey('Issue')
    user = models.ForeignKey(User)
    text = models.TextField()


class CommentVote(TimestampsModel):
    voter = models.ForeignKey(User)
    comment = models.ForeignKey('Comment')

    class Meta:
        unique_together = ('voter', 'comment')

comics/reader/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, get_object_or_404, render
from django.contrib.auth.views import login
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView

from braces.views import LoginRequiredMixin

from .models import Comic
from .models import Page


def custom_login(request, *args, **kwargs):
    if request.user.is_authenticated():
        return redirect('reader:comic_list')
    else:
        return login(request, *args, **kwargs)


class ComicBookListView(LoginRequiredMixin, ListView):
    model = Comic
    template_name = 'reader/comic_list.html'
    context_object_name = 'comic_list'
comic_list = ComicBookListView.as_view()


class ComicBookDetailView(LoginRequiredMixin, DetailView):
    model = Comic
    queryset = Comic.objects.select_related()
    template_name = 'reader/comic_detail.html'
    context_object_name = 'comic'
comic_detail = ComicBookDetailView.as_view()

@login_required
def page(request, slug, issue, number):
    template_name = 'reader/page.html'
    page = get_object_or_404(Page, page_number=number, issue__number=issue, issue__comic__slug=slug)
    return render(request, template_name, {'page': page})

comics/reader/templates/reader/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}{% endblock title %}</title>
    {% block css %}
        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">

        <!-- Optional theme -->
        <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap-theme.min.css">
    {% endblock css %}
</head>
<body>
  <div class="container">{% block content %}{% endblock content %}</div>

{% block javascript %}
    <!-- Latest compiled and minified JavaScript -->
    <script src="//code.jquery.com/jquery-2.1.0.min.js"></script>
    <script src="{% static '//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js' %}"></script>
{% endblock javascript %}
</body>
</html>

comics/reader/templates/reader/comic_detail.html
{% extends 'reader/base.html' %}

{% block content %}
  <h3>Issues</h3>
  <div class="small col-md-offset-11">
    <a href="{% url 'reader:comic_list' %}">Back to comics</a>
  </div>
  {% for issue in comic.issue_set.all %}
    <div class="row">
      <div class="col-md-12">
        <a href="{% url 'reader:page' issue.comic.slug issue.number 1 %}">{{ issue.number }} - {{ issue.title }}</a>
      </div>
    </div>
  {% endfor %}
{% endblock content %}

comics/reader/templates/reader/comic_list.html
{% extends 'reader/base.html' %}

{% block content %}
  {% for comic in comic_list %}
    <div class="row">
      <h3><a href="{% url 'reader:comic_detail' comic.slug %}">{{ comic.name }}</a></h3>
      <p>{{ comic.description }}</p>
      <div class="col-md-5">
        <a href="{% url 'reader:comic_detail' comic.slug %}"><img src="{% if comic.cover %}{{ comic.cover.url }}{% else %}http://placehold.it/350x150{% endif %}"/></a>
      </div>
    </div>
  {% endfor %}
{% endblock content %}

comics/reader/templates/reader/login.html
{% extends "reader/base.html" %}

{% block css %}
    {{ block.super }}
    <style>
    body {
      padding-top: 40px;
      padding-bottom: 40px;
      background-color: #eee;
    }

    .form-signin {
      max-width: 330px;
      padding: 15px;
      margin: 0 auto;
    }
    .form-signin .form-signin-heading,
    .form-signin .checkbox {
      margin-bottom: 10px;
    }
    .form-signin .checkbox {
      font-weight: normal;
    }
    .form-signin .form-control {
      position: relative;
      height: auto;
      -webkit-box-sizing: border-box;
         -moz-box-sizing: border-box;
              box-sizing: border-box;
      padding: 10px;
      font-size: 16px;
    }
    .form-signin .form-control:focus {
      z-index: 2;
    }
    .form-signin input[type="email"] {
      margin-bottom: -1px;
      border-bottom-right-radius: 0;
      border-bottom-left-radius: 0;
    }
    .form-signin input[type="password"] {
      margin-bottom: 10px;
      border-top-left-radius: 0;
      border-top-right-radius: 0;
    }
    </style>
{% endblock css %}

{% block content %}


    <div class="container">

      <form class="form-signin" role="form" method="post" action="{% url 'reader:login' %}">
        {% if form.errors %}
        <p>Nombre de usuario o contraseña incorrecta. Intente de nuevo.</p>
        {% endif %}
        {% csrf_token %}
        <h2 class="form-signin-heading">Por favor inicie sesion</h2>
        <input type="text" class="form-control" placeholder="Usuario" required autofocus name="{{ form.username.name }}">
        <input type="password" class="form-control" placeholder="Contraseña" required name="{{ form.password.name }}">
        <button class="btn btn-lg btn-primary btn-block" type="submit">Iniciar sesion</button>
          <input type="hidden" name="next" value="{{ next }}" />
      </form>

    </div> <!-- /container -->

{% endblock %}

comics/reader/templates/reader/page.html
{% extends 'reader/base.html' %}

{% block content %}
  <div class="row">
    <h3><a href="{% url 'reader:comic_detail' page.issue.comic.slug %}">#{{ page.issue.number }} - {{ page.issue.title }}</a></h3>
  </div>
  <div class="row">
    <div class="col-md-1"><a href="{{ page.before }}">Before</a></div>
    <div class="col-md-offset-10 col-md-1"><a href="{{ page.next }}">Next</a></div>
  </div>
  <div class="row">
    <div class="col-md-12"><img src="{{ page.image.url }}" /></div>
  </div>

{% endblock content %}